name: Shuttle Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          working-directory: "."
          name: "calendarbot"
          cargo-shuttle-version: "0.38.0"
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            APPLICATION_ID = '${{ secrets.APPLICATION_ID }}'
            CLIENT_ID = '${{ secrets.CLIENT_ID }}'